### ISSUE TITLE
timeout errors are not working correctly for reader/writer

### ISSUE THREAD

**Issue by ianthpun** [segmentio/kafka-go#614] opened 2021-03-08 20:48 UTC
**Describe the bug**

We've noticed that we're often getting a reader/producer error that should techincally be returning a `RequestTimedOut`. 
The logs were seeing here are from https://github.com/segmentio/kafka-go/blob/master/reader.go#L1332
```
the kafka reader got an unknown error reading partition 9 of SOME_TOPIC at offset 3: read tcp IP_ADDRESS:60504->IP_ADDRESS:21948: i/o timeout
--
```

we do notice these errors are returning faster than from the `Deadline` variable we've set, meaning it's likely why it's bypassing the `checkTimeoutErr` in order for it to return the `RequestTimedOut` message.

**Kafka Version**
2.6.1

**Additional context**
We're using aiven kafka as our broker.

**Comment by dominicbarnes** [comment] 2021-03-12 19:02
We're looking into this and we suspect that hitting a network timeout in that `*reader` means that the underlying connection likely cannot be re-used, so we're hoping that `*Reader` would properly retry and continue on from there.

What sort of `Deadline` configuration are you setting? We've come across a [hard-coded 10s deadline](https://github.com/segmentio/kafka-go/blob/master/reader.go#L1415) which could be why it shows up sooner than your own deadline. It might be the case that we simply need to respect the configuration set, which might clear up some confusion here.

**Comment by ianthpun** [comment] 2021-03-14 18:41
we currently our `maxWait` to 10 seconds and are still seeing this issue

**Comment by ianthpun** [comment] 2021-03-14 18:50
anoter issue we've noticed is that the `produce` call on writers doesn't seem to be handling the `i/o timeout` error correctly either. `Writer.produce` takes in a brand new `ctx.Background()` to produce, which, using the default timeout would be 10 seconds. However, we are still seeing these types of errors come up:

```
error writing messages to TOPIC (partition 12): kafka.(*Client).Produce: dial tcp IP:21948: i/o timeout
--
```
which aren't handled correctly in the for loop, as it never retries because this error is not considered as `isTemporary` in `writeBatch`

**Comment by ianthpun** [comment] 2021-03-16 01:17
In order to fix the above, I realize you can also add the additional `isTimeout` check here https://github.com/segmentio/kafka-go/blob/4314b9ea42d3d93434a71644de340695785d5bd6/writer.go#L780-L782 . 

So the code would be 
```
if !isTemporary(err) || !isTimeout(err) {
			break
		}
```

what are your thoughts?

**Comment by dominicbarnes** [comment] 2021-03-18 23:50
@ianthpun that sounds like it would be a worthwhile PR, would you mind setting that up?

I'd also like to see if we can find a way to add a test case for these changes. we should be able to synthesize a context cancellation easily enough, but the other failure modes may not be as cooperative. Once we have a PR to review, we can explore this in more detail.

**Comment by ianthpun** [comment] 2021-03-19 21:58
this pr https://github.com/segmentio/kafka-go/pull/616 should cover the producer, as `isTemporary` would work when the i/o timeout is unwrapped correctly. We can also include the consumer fix as well, unless you prefer splitting them up

**Comment by dominicbarnes** [comment] 2021-04-07 18:07
Now that #616 is merged, I will close this as I believe the issue is addressed. Feel free to re-open if this doesn't work as expected.

**Closed by dominicbarnes** 2021-04-07 18:07 UTC
Labels: bug
