### ISSUE TITLE
ConsumerGroup consuming only one partition. Also several consumer consuming same partition

### ISSUE THREAD

**Issue by elpadrinoIV** [segmentio/kafka-go#115] opened 2018-08-17 01:41 UTC
I tried to make the smallest example of the bug.

1. Create a topic with 2 partitions:
`./bin/kafka-topics.sh --zookeeper localhost:2181 --topic 2part --create --partitions 2 --replication-factor 1`
2. Publish consecutive messages to the topic
3. Consumer:
```
package main

import (
	"context"
	"fmt"
	"time"

	kafka "github.com/segmentio/kafka-go"
)

func main() {
	reader := kafka.NewReader(kafka.ReaderConfig{
		Brokers: []string{"localhost:9092"},
		GroupID: "sample",
		Topic:   "2part",
	})

	for {
		m, err := reader.FetchMessage(context.Background())
		if err != nil {
			continue
		}
		time.Sleep(1 * time.Second)
		fmt.Printf("P/O: %v/%v; %v: %v\n", m.Partition, m.Offset, string(m.Key), string(m.Value))

		reader.CommitMessages(context.Background(), m)
	}
}
```

Run 1 consumer:
```
$ ./test-consumer
P/O: 0/0; bd1f:	    Message number 0
P/O: 0/1; bd1f:	    Message number 2
P/O: 0/2; bd1f:	    Message number 4
P/O: 0/3; bd1f:	    Message number 6
P/O: 0/4; bd1f:	    Message number 8
P/O: 0/5; bd1f: 	Message number 10
```
Since there is only one consumer, he should read all the messages, not just the messages from one partition.
Then, when I run a second consumer:
```
$ ./test-consumer
P/O: 1/0; bd1f:	Message number 1
P/O: 1/1; bd1f:	Message number 3
P/O: 1/2; bd1f:	Message number 5
P/O: 1/3; bd1f:	Message number 7
P/O: 1/4; bd1f:	Message number 9
```

Finally, I run  a third consumer. Here are the logs (trimmed) of consumer 1, 2 and 3:
```
Consumer 1:
P/O: 0/26; bd1f:	Message number 52
P/O: 0/27; bd1f:	Message number 54
P/O: 1/12; bd1f:	Message number 25
P/O: 1/13; bd1f:	Message number 27
P/O: 1/14; bd1f:	Message number 29
P/O: 1/15; bd1f:	Message number 31
P/O: 1/16; bd1f:	Message number 33
P/O: 1/17; bd1f:	Message number 35
```
```
Consumer 2:
P/O: 1/12; bd1f:	Message number 25
P/O: 1/13; bd1f:	Message number 27
P/O: 1/14; bd1f:	Message number 29
P/O: 1/15; bd1f:	Message number 31
P/O: 1/16; bd1f:	Message number 33
P/O: 1/17; bd1f:	Message number 35
P/O: 1/18; bd1f:	Message number 37
...
P/O: 1/25; bd1f:	Message number 51
P/O: 1/26; bd1f:	Message number 53
P/O: 1/27; bd1f:	Message number 55
P/O: 1/28; bd1f:	Message number 57
P/O: 1/29; bd1f:	Message number 59
P/O: 1/30; bd1f:	Message number 61
P/O: 1/31; bd1f:	Message number 63
```
```
Consumer 3:
P/O: 0/26; bd1f:	Message number 52
P/O: 0/27; bd1f:	Message number 54
P/O: 0/28; bd1f:	Message number 56
P/O: 0/29; bd1f:	Message number 58
P/O: 0/30; bd1f:	Message number 60
P/O: 0/31; bd1f:	Message number 62
```

As you can see, consumer1 is getting some messages already processed by consumer 2 and 3.

Same test with kafka-console-consumer:
Run 1 consumer:
```
# Consumer 1
./bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic 2part --group aaa
Message number 1
Message number 2
Message number 3
Message number 4
Message number 5
Message number 6
Message number 7
Message number 8
Message number 9
```
Starting a 2nd consumer:
```
# Consumer 2
./bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic 2part --group aaa
Message number 11
Message number 13
Message number 15
Message number 17
Message number 19
```
Meanwhile, on consumer 1:
```
# Consumer 2
...
Message number 7
Message number 8
Message number 9
Message number 10
Message number 12
Message number 14
Message number 16
Message number 18
```

As you can see, when there was only one consumer, he consumed all the messages. When the second consumer appeared, each started consuming from one partition only.
If you stop consumer 2, consumer 1 starts reading from both partitions again.
If instead of stoping consumer 2, you add a third consumer, it may start consuming but one of the other 2 stops.

**Comment by achille-roussel** [comment] 2018-08-18 18:34
Thanks for reporting, I'm going to look into this.

**Comment by achille-roussel** [comment] 2018-11-25 08:05
This seems like a similar problem to #86 

@elpadrinoIV were you testing against Kafka 2?

**Comment by elpadrinoIV** [comment] 2018-11-25 14:44
@achille-roussel 
Sorry for not giving version details:
/opt/kafka/libs/kafka_2.12-2.0.0.jar

From /opt/kafka_2.12-2.0.0.tgz:
ec9b505eb3f665be02e61d507db9635e  /opt/kafka_2.12-2.0.0.tgz

**Comment by achille-roussel** [comment] 2018-11-25 22:17
This does sounds like an issue with Kafka 2 as the two bug reports seem to show similar behaviors and were both ran on Kafka 2.

This package has no automated tests with kafka 2 yet, so I wouldn't be surprised if those kinds of issue arise. 

If you want to contribute adding a test against Kafka 2 that would help track down what may have changed in later versions of Kafka that would have broken backward compatibility.

**Comment by achille-roussel** [comment] 2019-09-04 16:09
We did lots of work on the consumer group implementation in https://github.com/segmentio/kafka-go/pull/277 and fixed a couple of issues.

I'm not able to reproduce this bug anymore so I'll close it for now, feel free to reopen if it's still a problem.

**Closed by achille-roussel** 2019-09-04 16:09 UTC
Labels: question
