### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by abdullah-aghayan** [segmentio/kafka-go#588] opened 2021-01-16 11:21 UTC
**Describe the bug**
I tried to install the Kafka-go with the following command.

`go get -u github.com/segmentio/kafka-go`

But I got the following error that says

../github.com/segmentio/kafka-go/compress/lz4/lz4.go:38:29: undefined: lz4.Writer
../github.com/segmentio/kafka-go/compress/lz4/lz4.go:42:7: undefined: lz4.NewWriter
../github.com/segmentio/kafka-go/compress/lz4/lz4.go:58:21: undefined: lz4.Writer

**Comment by achille-roussel** [comment] 2021-01-16 19:05
I just tried that command on a brand new program and did get any issues.

Does you project have a dependency on a version of `github.com/pierrec/lz4` which is not compatible with the one kafka-go uses?

**Comment by abdullah-aghayan** [comment] 2021-01-16 19:24
I am trying to test kafka-go and learn some Kafka, and I don't have any other dependencies.

**Comment by achille-roussel** [comment] 2021-01-16 21:39
Could you share a minimal example to reproduce the behavior you're seeing?

**Comment by abdullah-aghayan** [comment] 2021-01-16 21:48
I have got that issue while I was installing the kafka-go. As I said, when I try to do `go get -u github.com/segmentio/kafka-go`, I get the following errors
`# github.com/segmentio/kafka-go/compress/lz4
../github.com/segmentio/kafka-go/compress/lz4/lz4.go:38:29: undefined: lz4.Writer
../github.com/segmentio/kafka-go/compress/lz4/lz4.go:42:7: undefined: lz4.NewWriter
../github.com/segmentio/kafka-go/compress/lz4/lz4.go:58:21: undefined: lz4.Writer`

I am trying to run the following example

`package main

import (
	"context"
	"log"

	"github.com/segmentio/kafka-go"
)

func main() {
	ctx = context.Background()
	producer(ctx)
}

func producer(ctx context.Context)  {
	w := &kafka.Writer{
		Addr: kafka.TCP('0.0.0.0:9092'),
		Topic: 'first_topic',
		Balancer: &kafka.LeastBytes{},
	}

	err := w.WriteMessages(ctx, kafka.Message{
		Key: []byte("test key"),
		Value: []byte("value value")
	})

	if err != nil {
		log.Fatal("faild to produce")
	}

	defer func() {
		if err := w.Close(); err != nil {
			log.Fatal("failed to close writer:", err)
		}
	}()
}`

**Comment by achille-roussel** [comment] 2021-01-20 04:38
Do you mind me asking which version of Go you are building with?

**Comment by abdullah-aghayan** [comment] 2021-01-20 08:27
I am using
go version go1.14.2 linux/amd64

**Comment by achille-roussel** [comment] 2021-01-20 20:14
Here's what I tried, I'm not getting any errors:

```
$ mkdir /tmp/test
$ cd /tmp/test
$ cat main.go
package main

import (
	"context"
	"log"

	"github.com/segmentio/kafka-go"
)

func main() {
	ctx = context.Background()
	producer(ctx)
}

func producer(ctx context.Context) {
	w := &kafka.Writer{
		Addr:     kafka.TCP("0.0.0.0:9092"),
		Topic:    "first_topic",
		Balancer: &kafka.LeastBytes{},
	}

	err := w.WriteMessages(ctx, kafka.Message{
		Key:   []byte("test key"),
		Value: []byte("value value"),
	})

	if err != nil {
		log.Fatal("faild to produce")
	}

	defer func() {
		if err := w.Close(); err != nil {
			log.Fatal("failed to close writer:", err)
		}
	}()
}
$ go mod init test
go: creating new go.mod: module test
$ go get -u github.com/segmentio/kafka-go
go: downloading github.com/segmentio/kafka-go v0.4.9
go: github.com/segmentio/kafka-go upgrade => v0.4.9
go: github.com/pierrec/lz4 upgrade => v2.6.0+incompatible
go: github.com/klauspost/compress upgrade => v1.11.7
go: github.com/golang/snappy upgrade => v0.0.2
```

**Comment by achille-roussel** [comment] 2021-02-12 19:17
Hello @abdullah-aghayan, were you able to track down the root cause of this issue, or are you still hitting it?

**Comment by achille-roussel** [comment] 2021-02-19 18:50
I'm going to close this because it seems to have been resolved, but feel free to reopen if you are still hitting this issue.

**Closed by achille-roussel** 2021-02-19 18:50 UTC
Labels: bug
