### ISSUE TITLE
"unsupported message version 2 found in fetch response" errror

### ISSUE THREAD

**Issue by frranck** [segmentio/kafka-go#128] opened 2018-10-17 08:57 UTC
Hello,
On big messages after increasing the KAFKA_MESSAGE_MAX_BYTES variable, I'm getting
"unsupported message version 2 found in fetch response" errors while doing a conn.ReadBatch,
Any idea what it mean ?

the code is there:
https://github.com/diadata-org/diadata/blob/master/pkg/dia/helpers/kafkaHelper/Kafka.go#L275

**Comment by achille-roussel** [comment] 2018-10-17 10:03
Hello @frranck Are you using kafka-go to both produce and consume into Kafka?

It could help to know which version of Kafka you are running as well!

**Comment by VictorDenisov** [comment] 2018-11-01 19:20
The problem can occur in every version from 0.11 and up:
https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchResponse

Read paragraph that starts with:
In Kafka 0.11, the structure of the 'MessageSet' and 'Message' were significantly changed. 

I don't yet quite understand how clients are supposed to recognize the Message set of version 1 and version 2.

**Comment by VictorDenisov** [comment] 2018-11-01 20:58
It looks like as we read offset, size, crc and version of the first message and see that version is 2 then we should stop parsing message and start parsing batch header after parsing batch header we can start parsing individual messages according to version 2 of the batch format.

**Comment by VictorDenisov** [comment] 2018-11-02 05:11
Though it's unclear how to reproduce it. I have a broker on my local machine with 1.1.0. version and it doesn't reproduce the issue.

**Comment by VictorDenisov** [comment] 2018-11-02 14:01
I have a reproduction.

**Comment by VictorDenisov** [comment] 2018-11-10 20:06
@frranck What value do you have in KAFKA_MESSAGE_MAX_BYTES . I'm troubles getting a stable reproduction of the issue.

**Comment by frranck** [comment] 2018-11-11 06:20
Hi @VictorDenisov I put  KAFKA_MESSAGE_MAX_BYTES = 10000000
https://github.com/diadata-org/diadata/blob/master/deployments/docker-compose.kafka.yml#L41

**Comment by VictorDenisov** [comment] 2018-11-19 02:31
@frranck can you try this branch: https://github.com/VictorDenisov/kafka-go/tree/new_v2_message_reader

**Comment by VictorDenisov** [comment] 2018-11-19 03:36
@achille-roussel according to fetch response v2 doc: https://kafka.apache.org/protocol#The_Messages_Fetch I don't see any MessageSetSize in its header.
However according to: https://github.com/segmentio/kafka-go/blob/master/read.go#L282
you are reading this value. I don't understand where in the protocol it's described. It also works in many cases. So it's even more mysterious to me. Could you please clarify it for me. Thanks in advance.

**Comment by achille-roussel** [comment] 2018-11-19 04:33
Sorry for the confusion, I think it’s an abuse that works because whether you have a message set or a record set, the size of the data structures follows the fetch response header, it was just more convenient to load it here.  

That being said, nothing prevents us from modifying this implementation detail if needed.

**Comment by stevevls** [comment] 2018-11-19 04:46
I've been able to reproduce this as well.  In some cases, even if you produce messages sets with a `MagicByte` of 1, the broker rewrites the message set to a `RecordSet` with `MagicByte` equal to 2. (https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets).  We do plan on adding support for reading `RecordSet` soon, and that should fix this issue.

**Comment by frranck** [comment] 2018-11-19 07:47
Thanks @VictorDenisov  I tried your branch and it solved the problem. :+1:

**Comment by VictorDenisov** [comment] 2018-11-19 17:09
@frranck It's only a test branch though. So, do really use it yet.

**Comment by VictorDenisov** [comment] 2018-11-19 17:11
@achille-roussel The thing is that I don't understand where this field comes from. It's not in the fetch response header, but also I don't understand where it's described in message set? Can you point me to a link? Thanks.

**Comment by VictorDenisov** [comment] 2018-11-20 04:12
It looks like it's described here: https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchResponse and less obviously described here: https://kafka.apache.org/protocol#protocol_common

**Comment by VictorDenisov** [comment] 2018-11-20 05:39
@frranck could you please give another try to that branch. I removed debug output from the code.

**Comment by VictorDenisov** [comment] 2018-11-27 05:17
@frranck Can you take a look at #146 and see if you can configure docker-compose to make kafka produce v2 messages.

**Comment by demeyerthom** [comment] 2018-12-05 10:12
I also started getting this issue after having changed `message.max.bytes` from the default of 1 MB to 5 MB. Subsequently the consumer started throwing the `unsupported message version 2 found in fetch response` when it hit the first message larger than 1 MB.

**Comment by VictorDenisov** [comment] 2018-12-06 15:02
@demeyerthom try increasing the allowed size of message in your consumer. From my experiments I can conclude that unless you have enabled compaction or compression on the broker, kafka doesn't really mangle your messages. So, you need to make sure that your producer and doesn't produce messages bigger than your consumer consumes at once. I saw this message version 2 when in fact the message was malformed.

**Comment by achille-roussel** [comment] 2019-03-21 21:35
This should have been fixed by https://github.com/segmentio/kafka-go/pull/146

**Closed by achille-roussel** 2019-03-21 21:35 UTC
