### ISSUE TITLE
Seeing - "Not Leader For Partition: the client's metadata are likely out of date" error

### ISSUE THREAD

**Issue by Gurshid** [segmentio/kafka-go#1078] opened 2023-02-16 11:20 UTC
**Describe the bug**

Getting the below error -
`[6] Not Leader For Partition: the client attempted to send messages to a replica that is not the leader for some partition, the client's metadata are likely out of date`

**Kafka Version**

kafka-go - v0.4.38

**To Reproduce**

This is happening in non-prod env where the load is around 3-4 rps only, or sometimes no messages for 30 mins
I have used the below config for my kafka reader

```
reader := kafka.NewReader(kafka.ReaderConfig{
		Brokers:     config.Brokers,
		GroupID:     config.GroupID,
		Topic:       config.Topic,
		StartOffset:  -1,
		MaxAttempts: 3,
		MaxWait:     time.Duration(86400) * time.Second,
		Dialer: &kafka.Dialer{
			Timeout:   10 * time.Second,
			DualStack: true,
			TLS:       tlsConfig,
		},
	})
```
I am using consumer groups (groupId) instead of partition and there are multiple pods running with the same consumer group.

**Expected Behavior**

It should consume messages

**Observed Behavior**

But while testing, i observed the below error -
`[6] Not Leader For Partition: the client attempted to send messages to a replica that is not the leader for some partition, the client's metadata are likely out of date`

**Additional Context**

While testing, only one pod is running with the given group id, and the messages were not present on the server, so the consumer was idle for about 30 mins. But as soon as the message started flowing, I started observing the above error.

I checked other [issues](https://github.com/segmentio/kafka-go/issues/433), and it says that the metadata needs to be updated. But how do I do this? Since, in this thread, it says how to update it when partition is used, but how to do when one uses group id and not partition? Please share an example on how to achieve this.

**Questions**

1. How can I resolve this and what needs to be done to prevent this?
2. Also, if the load is high, will I observe these errors then also? Because on prod, our load is around 2K-3K rps.

**Comment by dominicbarnes** [comment] 2023-02-24 18:20
We noticed your `MaxWait` is configured to 24 hours, which is an excessively long time that no connection will remain open for. I believe the default is 10s, could you try using the default instead and seeing if the issue persists?

I suspect that the issue here is that kafka-go is blocked waiting for `MaxWait` due to the lack of message volume, but also seems likely that behind the scenes a rebalance occurs and we won't make forward progress on updating the internals, resulting in this error.

**Comment by Gurshid** [comment] 2023-02-27 08:55
@dominicbarnes I can update the maxWait and check, but what does this config mean? The documentation regarding this is not very clear. If I am not using batching at my end, will this config affect me in any way?

Also, if the partition metadata expires, how do I update it? I see in this [thread](https://github.com/segmentio/kafka-go/issues/311#issuecomment-511475585) that using `ReadPartitions` will update the metadata, but how do I use it with Kafka reader? It is being accessed only via conn.

**Comment by dominicbarnes** [comment] 2023-04-28 16:39
The config indicates how long the underlying HTTP connection will remain open while it waits for new data, but if the connection gets closed underneath (ie: by the OS) it may not find right away if `MaxWait` is higher than the OS timeout. Readers and Writers are always batching behind the scenes, so it's always worth keeping that in mind.

I'm going to close this ticket, as I strongly suspect the high `MaxWait` is the underlying issue, but feel free to re-open if the issue isn't resolved.

**Closed by dominicbarnes** 2023-04-28 16:39 UTC

**Comment by celine-liew** [comment] 2023-04-28 18:28
HI @dominicbarnes  We've noticed the same error in  our service `audience-dest-service` for this sync request leading to a few sync failures after predictions team raised a slow sync issue. Though, eventually it did succeed after 3 separate failures on the same day: Apr 25, 2023 6:40 PM, Apr 25, 2023 8:55 PM, Apr 25, 2023 11:41 PM PST

**Kafka Version**
v0.4.39

This is in production environment.

This is the first time my team has encountered this error in our service so wondering what are some of the reasons that could lead to this error or if this error was just transient. We also recently did a kafka migration and wonder if this is more pertinent to the new kafka-personas cluster. 

https://retool.segment.com/apps/Personas/Sync%20Request%20Dashboard#syncRequestId=syr_2Ow8kStWb3Stul6IOa5XStblvrn

`Kafka write errors (1/1), errors: [[6] Not Leader For Partition: the client attempted to send messages to a replica that is not the leader for some partition, the client's metadata are likely out of date]`

cc @akhani18

**Comment by ve-weiyi** [comment] 2024-11-01 10:48
I have encountered the same problem, how can I solve it

**Comment by ve-weiyi** [comment] 2024-11-04 06:29
i have found the cause.i get a docker-compose file form github, the content is like this:
`
  kafka-0:
    ports:
      - "19094:9094"
    environment:
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:19094
  kafka-1:
    ports:
      - "29094:9094"
    environment:
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:19094
  kafka-2:
    ports:
      - "39094:9094"
    environment:
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:19094
`

three service both of listen 'EXTERNAL://localhost:19094'。
but i get another config is 

`
EXTERNAL://localhost:19094
EXTERNAL://localhost:29094
EXTERNAL://localhost:39094
`

when i run this config, my service  is normal。

I am a beginner

**Comment by sachin-rafay** [comment] 2025-04-17 19:46
I am getting the same error with AWS MSK. 

kafka-go v0.4.47

`w := &kafka.Writer{
		Addr:         kafka.TCP(brokers...),
		Balancer:     &kafka.LeastBytes{},
		RequiredAcks: kafka.RequireOne,
		BatchTimeout: option.batchTimeout,
		BatchSize:    option.batchSize,
		Async:        true,
		Completion: func(messages []kafka.Message, err error) {
			if err != nil {
				for _, message := range messages {
					logger.Error("Failed to write event", map[string]any{
						"error":     err,
						"topic":     message.Topic,
					})
				}
			}
		},
	}`

**Comment by sachin-rafay** [comment] 2025-04-22 10:27
This happened because my k8s pods were running behind istio sidecar. Bypassing the sidecar for kafka traffic solves this issue for me.
