### ISSUE TITLE
FetchMessage blocking after errors

### ISSUE THREAD

**Issue by joaodlf** [segmentio/kafka-go#1141] opened 2023-06-05 14:49 UTC
**Describe the bug**

This isn't particularly easy to debug, but I believe `FetchMessage` is permanently blocking after some errors are returned.

We had (what we believe to be) some networking issues on our side (nothing related go kafka-go), this resulted in a few errors in our logs, including the following from kafka-go:

```
failed to dial: failed to open connection to <host>: dial tcp <host>: i/o timeout
``` 

Also,

```
Leader Not Available: the cluster is in the middle of a leadership election and there is currently no leader for this partition and hence it is unavailable for writes
```

We had a consumer going with fairly high throughput, but after those errors in the logs, lag just kept going up. An app restart resumed the consumer group. The app has been written in a way to handle any error returned from `FetchMessage` (including context being closed) and to resume reading messages.

In what scenarios would this cause `FetchMessage` to  block indefinitely? 

**Kafka Version**

Confluent Platform
kafka-go v0.4.38

**Comment by petedannemann** [comment] 2023-06-30 17:16
@joaodlf could you please try to provide some code to reproduce this?

**Comment by petedannemann** [comment] 2023-06-30 17:19
Looks like a duplicate of this issue, please reference that issue for further discussion https://github.com/segmentio/kafka-go/issues/1133

**Closed by petedannemann** 2023-06-30 17:19 UTC
Labels: bug
