### ISSUE TITLE
Reader won't consume messages written >= 3 sec from the moment calling ReadMessage

### ISSUE THREAD

**Issue by LiorNeg** [segmentio/kafka-go#879] opened 2022-04-04 10:23 UTC
**Describe the bug**
calling ReadMessage results messages written after 3 sec or more, not getting consumed.

**Kafka Version**
Apache Kafka 3.0.0

**To Reproduce**
#### writer:
```
writer := &kafka.Writer{
			Addr:         kafka.TCP(cfg.Brokers...),
			Balancer:     &kafka.RoundRobin{},
			MaxAttempts:  5,
			BatchSize:    1,
			BatchBytes:   int64(cfg.MsgMaxBytes),
			BatchTimeout: time.Millisecond,
		},
```

#### reader:
```
func createKafkaReader(topic string, msgMaxBytes int, brokers ...string) *kafka.Reader {
	return kafka.NewReader(kafka.ReaderConfig{
		Brokers: brokers,
		Topic:   topic,
		GroupID: getGroupId(topic),
		MinBytes:          1,
		MaxBytes:          msgMaxBytes,
		MaxWait:           time.Second,
	})
}
```

**Expected behavior**
I expects reader to consume messages upon arrival.

**Additional context**
using `kafka-go v0.4.30`
`msgMaxBytes = 100MB`

**Comment by rhansen2** [comment] 2022-04-08 18:03
Hi @LiorNeg 

It would be helpful to enable logging to determine what is going on in your example. Since you're using consumer groups it can take time for the group to be setup before consuming messages (the details will be in the logs).  Additionally are you seeing the delay in messages between every call to ReadMessage or just the first?

**Comment by LiorNeg** [comment] 2022-04-10 20:24
2022/04/10 23:20:29 [kafka reader] entering loop for consumer group, 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers
2022/04/10 23:20:32 [kafka reader] joined group 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers as member ___kafka_test.test@ip-192-168-1-117.ec2.internal (github.com/segmentio/kafka-go)-53fa7665-8c17-47bd-92a9-c73a00dd58f8 in generation 1
2022/04/10 23:20:32 [kafka reader] selected as leader for group, 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers
2022/04/10 23:20:32 [kafka reader] using 'range' balancer to assign group, 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers
2022/04/10 23:20:32 [kafka reader] found member: ___kafka_test.test@ip-192-168-1-117.ec2.internal (github.com/segmentio/kafka-go)-53fa7665-8c17-47bd-92a9-c73a00dd58f8/[]byte(nil)
2022/04/10 23:20:32 [kafka reader] found topic/partition: 311ee62e-44e0-4122-af9d-45013cb90235-MM/0
2022/04/10 23:20:32 [kafka reader] assigned member/topic/partitions ___kafka_test.test@ip-192-168-1-117.ec2.internal (github.com/segmentio/kafka-go)-53fa7665-8c17-47bd-92a9-c73a00dd58f8/311ee62e-44e0-4122-af9d-45013cb90235-MM/[0]
2022/04/10 23:20:32 [kafka reader] joinGroup succeeded for response, 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers.  generationID=1, memberID=___kafka_test.test@ip-192-168-1-117.ec2.internal (github.com/segmentio/kafka-go)-53fa7665-8c17-47bd-92a9-c73a00dd58f8
2022/04/10 23:20:32 [kafka reader] Joined group 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers as member ___kafka_test.test@ip-192-168-1-117.ec2.internal (github.com/segmentio/kafka-go)-53fa7665-8c17-47bd-92a9-c73a00dd58f8 in generation 1
2022/04/10 23:20:32 [kafka reader] Syncing 1 assignments for generation 1 as member ___kafka_test.test@ip-192-168-1-117.ec2.internal (github.com/segmentio/kafka-go)-53fa7665-8c17-47bd-92a9-c73a00dd58f8
2022/04/10 23:20:32 [kafka reader] sync group finished for group, 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers
2022/04/10 23:20:32 [kafka reader] subscribed to topics and partitions: map[{topic:311ee62e-44e0-4122-af9d-45013cb90235-MM partition:0}:-2]
2022/04/10 23:20:32 [kafka reader] initializing kafka reader for partition 0 of 311ee62e-44e0-4122-af9d-45013cb90235-MM starting at offset -2
2022/04/10 23:20:32 [kafka reader] started heartbeat for group, 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers [3s]
2022/04/10 23:20:32 [kafka reader] started commit for group 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers
2022/04/10 23:20:32 [kafka reader] the kafka reader for partition 0 of 311ee62e-44e0-4122-af9d-45013cb90235-MM is seeking to offset 0
2022/04/10 23:20:33 [kafka reader] no messages received from kafka within the allocated time for partition 0 of 311ee62e-44e0-4122-af9d-45013cb90235-MM at offset 1
2022/04/10 23:20:33 [kafka reader] committed offsets for group 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers: 
	topic: 311ee62e-44e0-4122-af9d-45013cb90235-MM
		partition 0: 1

**Comment by LiorNeg** [comment] 2022-04-10 20:27
@rhansen2 seems like whats taking much time is joining the group:
2022/04/10 23:20:29 [kafka reader] entering loop for consumer group, 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers
2022/04/10 23:20:32 [kafka reader] joined group 311ee62e-44e0-4122-af9d-45013cb90235-MM-consumers as member [___kafka_test.test@ip-192-168-1-117.ec2.internal](mailto:___kafka_test.test@ip-192-168-1-117.ec2.internal) (github.com/segmentio/kafka-go)-53fa7665-8c17-47bd-92a9-c73a00dd58f8 in generation 1

I see this 3sec delay each time I create a new reader with the above config.

**Comment by rhansen2** [comment] 2022-04-22 17:43
Hi @LiorNeg thanks for your patience!

That 3 seconds looks like it could be potentially influenced by the HeartbeatInterval of the consumer group. Could you try changing the HeartbeatInterval on the ReaderConfig and let me know if it has any impact on the time it takes to join the group?

Thanks!

**Comment by rhansen2** [comment] 2022-04-22 23:59
Upon a bit more investigation I can only replicate the delay when the consumer group is being joined and it has existing members either still functional or not in which case Kafka will wait for the existing members in the group to rejoin. 

https://stackoverflow.com/questions/44555229/consumer-stuck-in-re-join seems to indicate this is expected behavior.

**Comment by rhansen2** [comment] 2022-05-06 16:03
Closing due to inactivity. Feel free to reopen if your issue persists.

**Closed by rhansen2** 2022-05-06 16:03 UTC
Labels: bug
