### ISSUE TITLE
Update least Byte balancer to fetch bytes from package itself if user does not provide bytes information

### ISSUE THREAD

**Issue by subhashcr** [segmentio/kafka-go#1081] opened 2023-02-21 08:14 UTC
For LeastByte Balancer processing, if leastBytesCounter information is not provided by caller then we are fetching partitions but not fetching their respective bytes count, this causing leastByte balancer to produce to same partition if caller does not set this values

link: https://github.com/segmentio/kafka-go/blob/f6986fb02ee7f8c6d6708da3f44b7ccf28fa435b/balancer.go#L101

**Comment by dominicbarnes** [comment] 2023-02-24 18:12
Can you provide a reproducible example, it is hard to identify what the underlying issue could be here. If we need additional test cases for `LeastBytes`, more information could inform how we proceed.

**Comment by subhashrouthu** [comment] 2023-02-25 05:18
sure Dominic Barnes,

Example:

we have topic "my_topic" with 2 partitions and we created 2 produces with the following writer config:

writer1 := kafka.NewWriter(kafka.WriterConfig{
		Brokers: config.KafkaBaseConfig.Brokers, Topic: topic, RequiredAcks: config.RequiredAcks,
		Async: config.Async, BatchSize: config.BatchSize, Balancer: &kafka.LeastBytes{},
		Logger: producer, ErrorLogger: producer,
	})

writer2 := kafka.NewWriter(kafka.WriterConfig{
		Brokers: config.KafkaBaseConfig.Brokers, Topic: topic, RequiredAcks: config.RequiredAcks,
		Async: config.Async, BatchSize: config.BatchSize, Balancer: &kafka.LeastBytes{},
		Logger: producer, ErrorLogger: producer,
	})

let's consider both partitions have o messages and when I push a message using writer1, the message goes to partition 1, now if we use writer2, it should go to partition2 since the bytes in partition 1 are greater than partition 2. But for the second message it's still going to partition 1, I debugged this case and found that while defining the balancer 
**Balancer: &kafka.LeastBytes{}**, if we are not defining leastBytesCounter structure, we are fetching partitions but we are not fetching byte size in each partition, causing messages to get produced to a single partition. can we get this method updated: https://github.com/segmentio/kafka-go/blob/f6986fb02ee7f8c6d6708da3f44b7ccf28fa435b/balancer.go#L98, so that it will fetch counters as well if not defined by default.

**Comment by subhashrouthu** [comment] 2023-03-28 10:54
any update here?

**Comment by dominicbarnes** [comment] 2023-04-14 17:10
The balancer only keeps track of what bytes it has seen in-memory, it does not coordinate with the brokers for byte information. Since you're creating a `&kafka.LeastBytes{}` for each writer, their state is also maintained separately.

If you want multiple writers to share this information, you should create 1 balancer and pass it to all of your writers. For example:

```golang
balancer := new(kafka.LeastBytes)

writer1 := kafka.NewWriter(kafka.WriterConfig{
  // ...
  Balancer: balancer
})

writer2 := kafka.NewWriter(kafka.WriterConfig{
  // ...
  Balancer: balancer
})

// ... writerN
```

I'll close this ticket for now, but feel free to re-open if that doesn't address your concern.

**Closed by dominicbarnes** 2023-04-14 17:10 UTC
