### ISSUE TITLE
example creating writer with tls in version 0.4

### ISSUE THREAD

**Issue by TomasVojacek** [segmentio/kafka-go#498] opened 2020-08-31 16:11 UTC
**I'm missing example of writer with TLS**
Original example use now deprecated newWriter and writerConfig

**Comment by aultimus** [comment] 2020-09-24 18:50
@TomasVojacek documentation for how to use tls with kafka-go was recently added to the readme [here](https://github.com/segmentio/kafka-go#tls-support). Does this answer your question?

**Comment by anti-peng** [comment] 2020-10-13 02:27
I'm doing this in v0.4.5, not sure if it's correct.
```
	dialer := kafka.DefaultDialer

	if TLS_ENABLED {
		dialer.TLS = &tls.Config{ ... your tls config ... }
	}

	if SASL_ENABLED {
		dialer.SASLMechanism = { ... your sasl mechanism ... }
	}

	transport := &kafka.Transport{
		Dial:        dialer.DialFunc,
		...,
	}

	writer := &kafka.Writer{
		Addr:         kafka.TCP(your.brokers...),
		Topic:        topic,
		...
		Transport:    transport,
	}
```

And please notice that you may find a bug here https://github.com/segmentio/kafka-go/issues/499

**Comment by aultimus** [comment] 2020-11-06 19:48
@anti-peng looks good to me, you can also use `kafka.NewWriter` if you don't want to specify a custom transport. Has this code been malfunctioning for you?

**Comment by TomasVojacek** [comment] 2020-11-06 21:59
It look good I do not have time to test it. We can close this.

**Comment by MadBookBro** [comment] 2020-12-08 09:53
@aultimus It's working OK for me. 
BTW, I'm not using `kafka.NewWriter` as it's been marked as `deprecated` in `v0.4.x`.

**Comment by mentalisttraceur** [comment] 2021-02-02 00:16
So are these the only two options right now? To use TLS or SASL with a `kafka.Writer`:

1. modify the global `kafka.DefaultDialer`, or
2. use deprecated `kafka.NewWriter` and `kafka.WriterConfig` APIs?

**Comment by mentalisttraceur** [comment] 2021-02-02 00:22
Okay, I found what looks like the "proper" new way to do this [in this comment on another issue](https://github.com/segmentio/kafka-go/issues/499#issuecomment-688695177):

```go
writer := &kafka.Writer{
	/* ... */
    	TLS: &tls.Config{},
	SASL: plain.Mechanism{
		Username: "yyy",
		Password: "zzz",
	},
	/* ... */
}
```

**Comment by mentalisttraceur** [comment] 2021-02-02 00:47
Okay, so if I'm understanding correctly, the "official" (non-deprecated) public API for `Writer` and `Reader` are now *different*: the `Writer` is created directly with a `Transport` object as one of its fields, the `Reader` is created through the `NewReader` function taking a `ReaderConfig` object with a `Dialer` object as one of its fields.

I understand that you're in a transition towards a consistent API, I just wish that the `README` had been updated to document the new non-deprecated way.

**Comment by mentalisttraceur** [comment] 2021-02-02 00:50
Hey @aultimus , am I missing something? Is there a reason why you recommended the now-deprecated approach using `NewWriter` and `WriterConfig`? Are there some pitfalls/regressions/differences versus using the new `Transport` as above that we should be aware of?

**Comment by aultimus** [comment] 2021-02-16 23:35
@mentalisttraceur I was looking at master before the update so my recommendation was likely based off of a prior version where it was not deprecated

**Comment by rhansen2** [comment] 2022-11-04 04:49
Looks like this has been done https://pkg.go.dev/github.com/segmentio/kafka-go#readme-tls-support

**Closed by rhansen2** 2022-11-04 04:49 UTC
Labels: documentation
