### ISSUE TITLE
How could I  set auto-offset-reset on restart the consumer

### ISSUE THREAD

**Issue by apexkaws911** [segmentio/kafka-go#93] opened 2018-04-26 04:02 UTC
r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:  []string{"Ip:9092"},
		GroupID:  "go_test",
		Topic:    "test",
		MinBytes: 10e3, // 10KB
		MaxBytes: 10e6, // 10MB
		//CommitInterval: time.Second,
	})
When I init the NewReader ,how could I set auto-offset-reset is earliest on restart ?

**Comment by niuzhifa** [comment] 2018-07-24 10:06
I had the same problem

**Comment by Pryz** [comment] 2018-07-25 20:41
What do you mean by `on restart` ?

Are you looking for https://godoc.org/github.com/segmentio/kafka-go#Reader.SetOffset ? 

```
Setting the offset ot -1 means to seek to the first offset. Setting the offset to -2 means to seek to the last offset.```

**Comment by barockok** [comment] 2018-11-22 16:14
`SetOffset` won't work for consumer group, how to set an option on consumer group so we can choose whether we want to start from "earliest" or "latest", which is the one that should be equivalent with `auto.offset.reset` in Kafka consumer config.

What to do when there is no initial offset in Kafka or if the current offset does not exist any more on the server (e.g. because that data has been deleted):earliest: automatically reset the offset to the earliest offsetlatest
--


What to do when there is no initial offset in Kafka or if the current offset does not exist any more on the server (e.g. because that data has been deleted):earliest: automatically reset the offset to the earliest offsetlatest
--

**Comment by achille-roussel** [comment] 2018-11-25 07:50
This issue seems to be a duplicate of #88 so I'll close it. Feel free to re-open if I'm mistaken.

**Closed by achille-roussel** 2018-11-25 07:50 UTC
Labels: duplicate
