### ISSUE TITLE
Consumer Group Offset Expiry

### ISSUE THREAD

**Issue by orn1983** [segmentio/kafka-go#435] opened 2020-04-27 11:01 UTC
When using a consumer group through a kafka.NewReader with the GroupID set, it seems that all my offset commits expire after a few minutes.

The offset expiry in Kafka is set to its default value (a week), so I'm really surprised to see this. I can see that the client is sending OffsetCommit and it is being received. If I reconnect before the expiry happens, it will resume at the correct location.

If I use the included kafka console consumer group client, the offsets do not expire until after the full week. I ran a tcpdump to see if there was a difference in how the clients were pushing the OffsetCommit, and it seems that there is an API version difference. I haven't been able to figure out whether the v2 OffsetCommit (which kafka-go seems to be using) is supposed to push an explicit expiry time or not (it is currently pushing 0, which I would assume lets Kafka decide), but it does not seem like the most recent OffsetCommit (v8) used by the console client is doing so (hard to tell for sure as Wireshark doesn't support this API version yet).

I've tested against Kafka 1.0.0 and 2.4.1 with identical results.

Perhaps I need to use kafka.NewConsumerGroup for this to work properly? I'm just using NewReader with GroupID set, as described in the README.

Here's how I'm connecting:
d := &kafka.Dialer{
  Timeout:   10 * time.Second,
  ClientID:  flagClientID,
  DualStack: false,
}
reader := kafka.NewReader(kafka.ReaderConfig{
  Brokers:     kafkaBrokers,
  Dialer:      d,
  GroupID:     flagConsumerGroup,
  Topic:       flagKafkaTopic,
  MinBytes:    50,
  MaxBytes:    1e6, // 1 MB
  Logger:      Trace,
  ErrorLogger: Error,
})
defer reader.Close()

for {
  m, _ := reader.ReadMessage(ctx)
  Trace.Printf("Received message at %v/%v/%v: %s\n", m.Topic, m.Partition, m.Offset, string(m.Value))
}

The resulting TRACE output describes that the offsets are being committed after each read:
TRACE: consumergroup.go:387: committed offsets for group testy-tester:
        topic: testytopic
                partition 0: 4

According to the source code, there is a RetentionTime for the consumer group in the default ConsumerGroup configuration, though that is stated to be 24h, and I'm seeing an expiry after only a few minutes.

Is this misdocumented, a bug, or am I doing something wrong?

**Comment by orn1983** [comment] 2020-04-27 11:14
Reflecting upon posting -- perhaps I'm conflating two terms into one? Is a consumer group created with a certain lifetime, and then offsets within said consumer groups have their own lifetime?

If that's the case, I'm guessing the default value of 24h for consumer groups documented (RetentionTime) is just wrong?

It's worth noting that if I use kafka-console-consumer, which makes the offsets last for a week instead of a few minutes, and subsequently use kafka-go's GroupConsumer, then wait a few minutes, then the committed offset will revert to the last committed value of the console consumer -- that is to say that kafka-go's offsets get lost, and we go back to the last known offset pushed by kafka-console-consumer.

**Comment by stevevls** [comment] 2020-04-27 16:35
Hi @orn1983 .  Thanks for the bug report.  I believe this is a duplicate of #393 .  We had the fix sitting on master but had not tagged a release in a while.  I just tagged `v0.3.6`, so please update to correct the behavior.  Please feel free to reopen the issue if it's still present after upgrading!

**Closed by stevevls** 2020-04-27 16:35 UTC
Labels: bug
