### ISSUE TITLE
Memory leak in reflect package

### ISSUE THREAD

**Issue by mhmtszr** [segmentio/kafka-go#1061] opened 2023-01-12 21:08 UTC
I realized memory increase in our application and I dumped the heap usage and saw that kafka-go library allocates a lot of heap memory.
![image](https://user-images.githubusercontent.com/35079195/212180996-45fcf7ff-a568-4efe-9019-cf6ef102700b.png)

In reflect.go file:
```
func makeArray(t reflect.Type, n int) array {
	return array{val: reflect.MakeSlice(reflect.SliceOf(t), n, n)}
}

func bytesToString(b []byte) string { return string(b) }
```

- Every makeArray function call allocates a new slice, we may use sync.pool here to decrease the allocation.
- bytesToString makes an unnecessary string allocation, we may use unsafe pointer to avoid allocation.

**Comment by shivansh-bb** [comment] 2023-03-03 07:12
I have observed similar issue and this memory is not released even after closing the writer and the transport.

**Comment by mhmtszr** [comment] 2023-03-03 07:14
@shivansh-bb you can look at https://github.com/search?q=repo%3Asegmentio%2Fkafka-go+unsafe&type=code building application with unsafe tag, reflect_unsafe.go may reduce your memory usage.

**Comment by shivansh-bb** [comment] 2023-03-03 07:46
Its using unsafe_NewArray yet allocating huge memory to objects that is not getting cleared on closing the writer.
PFA Attached memory profile

**Comment by rhansen2** [comment] 2023-03-03 20:18
Hi,

@mhmtszr Did building with unsafe solve your issue?

@shivansh-bb Is your memory profile of inuse objects or total allocated objects?

**Comment by mhmtszr** [comment] 2023-03-03 20:35
Hi @rhansen2 ,

I did build with unsafe but still there are huge amount of allocations.

**Comment by rhansen2** [comment] 2023-03-03 20:42
@mhmtszr, Given that the library allocates based on the amount of data being produced or consumed it's hard to say how much it should be allocating. How much memory are you seeing allocated relative to the amount of data being consumed or produced?

**Comment by shivansh-bb** [comment] 2023-03-06 08:40
> @shivansh-bb Is your memory profile of inuse objects or total allocated objects?
Hi @rhansen2 
profile was for the allocated inuse_space.

**Comment by mhmtszr** [comment] 2023-03-06 08:50
@rhansen2 not much, we are not consuming a lot of messages. Memory usage is being increased constantly.

**Comment by rhansen2** [comment] 2023-03-06 19:12
@mhmtszr @shivansh-bb Thanks for the additional context!

Given that it seems like you're seeing this behavior with both the reader and the writer are you able to provide runnable minimal reproductions of your issues? It would be helpful for me looking into the further so I can be sure I'm able to successfully reproduce what you're seeing.

**Comment by shivansh-bb** [comment] 2023-03-14 07:00
@rhansen2 yes sure, give me sometime. will share a working sample here.

**Comment by rhansen2** [comment] 2023-04-28 16:36
Closing this issue for now due to inactivity. Please feel free to reopen if you're continuing to experience this issue or if you're able to provide a reproduction, thanks!

**Closed** 2023-04-28 16:35 UTC
Labels: bug

**Comment by JohnCulver** [comment] 2024-04-22 21:25
@shivansh-bb Were you ever able to solve this problem?
I have the same issue and have not been able to figure it out.
