### ISSUE TITLE
Restarting Consumer replays consumed messages when GroupID is set

### ISSUE THREAD

**Issue by saminahbab** [segmentio/kafka-go#896] opened 2022-04-26 07:19 UTC
**Consumer offset is not respected when using Consumer GroupID**

When the kafka consumer is set up such as this: 

```
func CreateKafkaReader(topic string, address string, consumerGroup string) *kafka.Reader {

	r := kafka.NewReader(kafka.ReaderConfig{
		Brokers:  []string{address},
		GroupID:  consumerGroup,
		Topic:    topic,
		MinBytes: 10e3, // 10KB
		MaxBytes: 10e6, // 10MB
	})

	return r

}
```
Restarting the code makes the consumer replay all messages in the topic, including ones that have already been processed. 

The logic for consuming messages is shown below 
```
	msg, err := a.Consumer.ReadMessage(context.Background())
        /// processing code comes here 
       a.Consumer.CommitMessages(context.Background(), msg)
```
**Kafka Version**

> * What version(s) of Kafka are you testing against?
3.0.0
> * What version of kafka-go are you using?
0.4.31
**To Reproduce**

**Expected Behavior**

When I restart the app with the consumer, the last `unread` message is used to consume from

**Observed Behavior**

The oldest message is used as the starting point.

**Comment by achille-roussel** [comment] 2022-04-29 17:08
Hello @saminahbab, thanks for reaching out!

The behavior you describe seems unexpected and not something we have observed before. Would you be able to share a fully reproducible test case?

**Comment by achille-roussel** [comment] 2022-06-24 17:30
I'm going to close this issue since there has been on activity. Feel free to reopen if it requires further discussion.

**Closed by achille-roussel** 2022-06-24 17:30 UTC
Labels: bug
