### ISSUE TITLE
Question: what would happen if produce a mount of messages by an async Writer to a Kafka cluster without response？

### ISSUE THREAD

**Issue by 3AceShowHand** [segmentio/kafka-go#831] opened 2022-01-26 16:49 UTC
**Describe the solution you'd like**

Consider the following steps
* Use an async Writer to write messages to a one node kafka cluster，this will buffer messages in the Writer I think.
* Before the Writer flush all messages to the kafka，`kill -s STOP` the kafka broker，this mocks that the broker can not send response
* The Writer should receive errors quickly
* User application code try to close the Writer by receiving the error

**Expected Behavior

Before the Writer return from `Close()`, it may try to flush all messages to the kafka，but now it will cost a lot of time, and finally failed, just as what we meet by using another kafka client library, which blocked more than one hour without returned.

What we really expected is, provide the ability that when the `Close()` called, drop all buffered messages, and return as soon as possible, to prevent block the application.

Hope get response from the community, thanks.

**Comment by 3AceShowHand** [comment] 2022-01-26 16:55
For the current implementation，is there any way to prevent close blocked a long time？

**Comment by dominicbarnes** [comment] 2022-02-04 07:37
Looking over the recent commit history, it looks like https://github.com/segmentio/kafka-go/pull/805 included a fix to a problem with closing async writers that sounds like it could be related to what you are describing here. This fix was deployed with v0.4.26 only a few weeks ago, so if you are not already on this version, would you mind trying to upgrade to see if that fixes?

If you were already using at least v0.4.26 or even after upgrading you are still experiencing this problem, we can troubleshoot further. (it may be possible to create a reproducible test case out of this if it's needed)

**Comment by dominicbarnes** [comment] 2022-10-14 16:50
I'm closing this issue as we haven't received a response for some time, feel free to re-open if you have more details.

**Closed by dominicbarnes** 2022-10-14 16:50 UTC
Labels: enhancement, question
