### ISSUE TITLE
Issue with Segmentio's Consumer Group Metadata Decoder Compatibility

### ISSUE THREAD

**Issue by aratz-lasa** [segmentio/kafka-go#1196] opened 2023-09-25 12:18 UTC
**Describe the bug**

Segmentio's consumer group metadata decoder is not compatible with [Confluent (librdkafka)](https://github.com/confluentinc/confluent-kafka-go) and [Franz-go](https://github.com/twmb/franz-go/tree/master)'s format, which prevents running segmentio clients together with other clients.

The issue arises from Segmentio's failure to read and decode the latest extra fields of the consumer group metadata. In particular, it lacks compatibility with the format used by Confluent and Franzgo, making it unable to decode the metadata and compute the assignments if the Segmentio client is selected as the leader.

Here's a brief overview of the problem:

1. Segmentio does not read/decode the latest extra fields of the metadata (source: [Franzgo Code](https://github.com/twmb/franz-go/blob/c9d2351dbcf7f027bca30127269eedaa2904579b/pkg/kmsg/generated.go#L1544)).

2. After decoding, Segmentio checks whether there is any remaining byte, and if there is, it raises an error (source: [Segmentio Code](https://github.com/segmentio/kafka-go/blob/9ecb9d2f7da50f4e23e4ef40270751820e154c81/consumergroup.go#L1058)). The problem is that there will always be remaining bytes, because it does not read the latests fields.

This incompatibility results in Segmentio's inability to handle the metadata when it becomes the leader, causing problems in decoding and assignment computation.

**Kafka Version**

From 2.4.0 onwards. That's the version where [KIP-429](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol) was introduced and extended the metadata for the first time.

**To Reproduce**
It is as simple as running a segmentio consumer with librdkafka or franz-go consumer. As soon as the segment client is selected the leader, the segment consumer will shout an error and the consumer group will not progress.

The error will be: `Failed to join group X: unable to read metadata for member, Y: %!w(<nil>)`

**Comment by petedannemann** [comment] 2023-09-25 13:34
Thanks for reporting this @aratz-lasa, this looks like a duplicate of https://github.com/segmentio/kafka-go/issues/1156

**Closed** 2023-09-27 14:56 UTC
Labels: bug
