### ISSUE TITLE
WriteMessages blocks indefinitely without returning error

### ISSUE THREAD

**Issue by natemurthy** [segmentio/kafka-go#110] opened 2018-07-07 22:11 UTC
I have an application that writes to a Kafka broker. It is configured with most of the default configuration in place like so:
```
config := kafka.WriterConfig{
	Brokers: brokerlist,
	Topic:   topic,
}

w := kafka.NewWriter(config)
```
I've observed `w.WriteMessages(ctx, msgs)` block without any apparent reason. I've been looking at the code to understand the underlying implementation. In what cases would this function block forever? If any maintainers can help diagnose this with me, it would be greatly appreciated.

**Comment by achille-roussel** [comment] 2018-07-07 23:07
Would you be able to provide stack traces of your program to understand where exactly it fails to make progress? You can do so in Go by sending SIGQUIT which causes the program to exit and output the stack traces of all goroutines. Otherwise you can use pprof to get the stack traces exposed on a HTTP endpoint without having to terminate your application.

It would be useful to have more details on your use case, like how many messages are you attempting to produce? Does the code block on the first write? Which version of Kafka are you running against? Do you have a minimal example that we could use to reproduce the problem?

**Comment by dgregoire** [comment] 2018-07-07 23:53
I believe #92 might be related - with the default `BatchSize` of 5 I also observe blocking until ctx is canceled or hits the deadline and things start working with `BatchSize` set to 1.

**Comment by natemurthy** [comment] 2018-07-08 18:09
@achille-roussel Here is a pprof heap dump of the application: https://pastebin.com/wmqYpgkW

@dgregoire I haven't adjusted the default `BatchSize` or wrapped the background parent context that I pass to `WriteMessages` with a timeout. My understanding of the same logic also unclear as I would expect this function to return with error after reaching the maximum number of attempts.

I should also note, that in roughly 5% of my write attempts this function returns with `EOF`, which I'm also having a hard time understanding.

**Comment by natemurthy** [comment] 2018-07-08 18:21
Could the state of the network connection to the Kafka brokers or the brokers themselves block the writers? If so, what steps would you recommend I follow to diagnose?

**Comment by dgregoire** [comment] 2018-07-08 21:59
@natemurthy the example I posted uses a context with timeout of 300ms, `batchSize` of 5, in synchronous producer with 1 required ack, sending a batch of one message.

If the issue is similar, you should stop observing the blocking by adjusting your `batchSize` to 1.

**Comment by natemurthy** [comment] 2018-07-09 12:03
Question for `kafka-go` devs though: why are we observing such in the first place? And why does adjusting the batch size have such an effect?

**Comment by abraithwaite** [comment] 2018-07-09 23:13
Which version of Kafka are you using?

**Comment by natemurthy** [comment] 2018-07-09 23:36
Apache Kafka 0.11.0.0

**Comment by abraithwaite** [comment] 2018-07-17 03:43
I think it's possible that one of the requests is using the wrong API version.  Keep an eye on this PR and try it when it gets merged:

https://github.com/segmentio/kafka-go/pull/80

Sorry we don't have a better answer around this.  I believe it's mostly been tested against 1.0.x.  (someone more knowledgable please correct me if wrong).

**Comment by dgregoire** [comment] 2018-07-19 13:37
@abraithwaite in #92 I was testing against 1.0.1

My understanding of the situation is that if you're an async producer, using the default batch size of  `5`, then you need to send out batches of `5` messages otherwise the producer is unable to proceed and blocks indefinitely - does that make sense?

**Comment by natemurthy** [comment] 2018-07-30 16:18
Hi @abraithwaite, what's the update on #80 ? There hasn't been any activity since 2018 July 13.

**Comment by achille-roussel** [comment] 2018-11-25 07:32
@dgregoire the batch timeout should prevent this from happening as it would periodically flush the messages (the default is every 1s), see https://github.com/segmentio/kafka-go/blob/fd74aea08fe1ca25fdfd51681798dd76821f12b6/writer.go#L600

@natemurthy from looking at the stack traces you provided it looks like the code may have been blocked on establishing connections to kafka? (quite a bit has changed in those files unfortunately so it's hard to correlate the line numbers without knowing which commit your code was built against).

**Comment by dgregoire** [comment] 2018-12-26 23:38
@achille-roussel the test I was doing has many (1000s/s) concurrent writes of one message using the same `Producer` and they all blocked indefinitely until I set batch size to `1`.

I'll try retesting with the latest version and update this.

**Comment by natemurthy** [comment] 2018-12-28 00:48
As much as I appreciate the effort to write a native Go library for Kafka clients, I have opted to use the confluent-kafka-go for my applications. Thank you and feel free to close this out unless others are still tracking this issue.

**Comment by dgregoire** [comment] 2018-12-28 00:53
@natemurthy I'm still tracking it and plan to re-test with the same conditions against current head

**Comment by achille-roussel** [comment] 2019-03-21 21:28
We can't reproduce the issue so we'll close for now, but if you have more details to share about the code or your environment feel free to reopen 👍

**Closed by achille-roussel** 2019-03-21 21:28 UTC

**Comment by dgregoire** [comment] 2019-03-22 23:57
@achille-roussel 

I revisited this today - i still see the same issue, `WriteMessages` with a batch of messages, for instance:

```go
func (p *SyncProducer) run() {
	// drain the channel
	// and flush messages
	for {
		select {
		case msgs := <-p.messages:
			// nil slice is possible
			if len(msgs) == 0 {
				continue
			}
			err := p.writer.WriteMessages(context.Background(), msgs..)
			// metrics
			sentMessages.WithLabelValues(err.Error()).Add(float64(len(msgs)))
		}
	}
}
```

this code will block forever on the `WriteMessages` function. The init code is like this:

```go
	w := kafka.NewWriter(kafka.WriterConfig{
		Brokers:      brokers,
		Topic:        topic,
		Balancer:     &kafka.Hash{},
		RequiredAcks: requiredAcks,
		BatchSize:    batchSize,
		CompressionCodec: snappy.NewCompressionCodec(),
	})
```

I'm using go v1.12 and kafka-go v0.2.2 with kafka v1.0.1. I tried setting batch size to 1, 5, 100, it makes no difference. I know the kafka broker configuration works because using the same `Writer` with a batch size of 1, and sending only ONE message works.

What do you advise?

**Comment by mhughes** [comment] 2020-08-28 16:52
Sorry for resuscitating this but I believe the underlying issue is the following.
This behaviour seems to correspond when handling a NotEnoughReplicas error with ack=all .
