### ISSUE TITLE
Plain SASL mechanism fails for writer

### ISSUE THREAD

**Issue by cemremengu** [segmentio/kafka-go#533] opened 2020-10-10 19:48 UTC
**Describe the bug**
Plain auth mechanisim producing the error below on the server, failing to auth

`Invalid SASL/PLAIN response: expected 3 tokens, got 4) (org.apache.kafka.common.network.Selector)`

**Kafka Version**
cp-kafka (docker) 6.0.0

**To Reproduce**
Try creating a new writer with plain mechanism

```golang
	w := kafka.NewWriter(kafka.WriterConfig{
		Brokers:          opts.Brokers,
		Topic:            "xxx",
		Balancer:         &kafka.RoundRobin{},
		BatchSize:        500,
		BatchTimeout:     10 * time.Millisecond,
		CompressionCodec: snappy.NewCompressionCodec(),
		Dialer: &kafka.Dialer{
			Timeout: 10 * time.Second,
			SASLMechanism: plain.Mechanism{
				Username: opts.Username,
				Password: opts.Password,
			},
		},
	})
```

**Expected behavior**
Dialer by itself works fine

```golang
	mechanism := plain.Mechanism{
		Username: "admin",
		Password: "xxxx",
	}

	dialer := &kafka.Dialer{
		Timeout:       10 * time.Second,
		DualStack:     true,
		SASLMechanism: mechanism,
	}

	conn, err := dialer.DialContext(context.Background(), "tcp", url)
````

**Additional context**
Seems like `authorizationIdFromClient` is missing ?

https://github.com/a0x8o/kafka/blob/master/clients/src/main/java/org/apache/kafka/common/security/plain/PlainSaslServer.java#L93

**Comment by godwhoa** [comment] 2020-11-01 19:43
Was able to reproduce this locally so did some digging, v0.4.1 to v0.4.5 have this bug. v0.3.x, v0.4.0 and >=v0.4.6 don't have this bug.

**Comment by achille-roussel** [comment] 2021-02-12 20:22
Thanks for reporting @cemremengu, and following up on the issue @godwhoa!

Since this has been fixed in later versions of kafka-go, I will be closing the issue. Feel free to reopen if you are still encountering problems.

**Closed by achille-roussel** 2021-02-12 20:22 UTC
Labels: bug
