### ISSUE TITLE
failed to find any partitions for topic

### ISSUE THREAD

**Issue by hryamzik** [segmentio/kafka-go#74] opened 2018-02-23 08:26 UTC
I have to post messages for different topics so my send function looks like this:

```go
func sendToKafka(msg syslogparser.LogParts) {
	w := kafka.NewWriter(kafka.WriterConfig{
		Brokers:  brokerFlags,
		Topic:    fmt.Sprintf("%s.logs", msg["tag"]),
		Balancer: &kafka.LeastBytes{},
	})

	err := w.WriteMessages(context.Background(),
		kafka.Message{
			Key: []byte("msg"),
			Value: []byte(
				fmt.Sprintf("some content"),
			),
		},
	)
	CheckError(err)
	w.Close()
}
```

For the first time new topic fails with `failed to find any partitions for topic`. Next time works just fine.

May be related to #53.

**Comment by achille-roussel** [comment] 2018-02-23 08:29
Hello @hryamzik 

Do you have topic auto-creation enabled on your kafka servers? In that case topic creation may be delayed and cause the first writes to fail.

**Comment by hryamzik** [comment] 2018-02-23 08:32
@achille-roussel I believe auto-creation is enabled, that also explains why next attempt succeeds. However I'm not sure how to properly handle this issue to avoid data loss.

**Comment by achille-roussel** [comment] 2018-02-24 05:01
Have you tried checking the error from `WriteMessages` and have the program attempt to publish the messages again a little later?

**Comment by hryamzik** [comment] 2018-02-26 08:27
That's the plan but I would expect this to be handled on library level.

**Comment by hryamzik** [comment] 2018-02-27 08:35
FYI: retry works only if a writer is recreated as well.

**Comment by buixor** [comment] 2018-02-27 10:46
Hello,

Maybe the `Writer` can expose the `(*Conn) CreateTopics` function ? I encountered the same issue as @hryamzik :)

**Comment by aerostitch** [comment] 2018-03-21 23:08
Hi guys,

I've tested with a docker-compose locally with the following code and the auto-creation of topics can take more than 10 seconds. That might be a lot of message kept in memory especially for short-living applications. If your program just pushes a few messages `Ansynchronously` in a partition that does not exists the 1st time and then ends, we can't be sure the messages are pushed if we hide that part in the `WriteMessage` function. Is that an acceptable trade off if we just add a note in the documentation?
```go
package main

import (
  "context"
  "github.com/segmentio/kafka-go"
  "log"
  "time"
)

func sendToKafka(topics []string, msgs map[string]string) {
  for _, topic := range topics {
    w := kafka.NewWriter(kafka.WriterConfig{
      Brokers:  []string{"localhost:9092"},
      Topic:    topic,
      Balancer: &kafka.LeastBytes{},
    })

    for key, msg := range msgs {
      err := w.WriteMessages(context.Background(),
        kafka.Message{
          Key:   []byte(key),
          Value: []byte(msg),
        },
      )
      if err != nil {
        log.Printf("Topic %s, Key: %s, Value: %s, Error: %s", topic, key, msg, err)
        time.Sleep(5 * time.Second)
      }
    }
    w.Close()
  }
}

func main() {
  topics := []string{"topicA", "topicB", "topicC", "topicD"}
  msgs := map[string]string{"foo": "bar", "artist": "song", "cat": "rule the world", "dogs": "serve and protect"}
  sendToKafka(topics, msgs)

  // Cleanup
  conn, _ := kafka.DialLeader(context.Background(), "tcp", "localhost:9092", topics[0], 0)
  conn.DeleteTopics(topics...)
  conn.Close()
}
```

Run logs that show how much time it can take to get a message in:
```
$ go run main.go
2018/03/21 15:53:17 Topic topicA, Key: artist, Value: song, Error: failed to find any partitions for topic topicA
2018/03/21 15:53:22 Topic topicA, Key: cat, Value: rule the world, Error: failed to find any partitions for topic topicA
2018/03/21 15:53:27 Topic topicA, Key: dogs, Value: serve and protect, Error: failed to find any partitions for topic topicA
2018/03/21 15:53:33 Topic topicB, Key: foo, Value: bar, Error: failed to find any partitions for topic topicB
2018/03/21 15:53:38 Topic topicB, Key: artist, Value: song, Error: failed to find any partitions for topic topicB
2018/03/21 15:53:43 Topic topicB, Key: cat, Value: rule the world, Error: failed to find any partitions for topic topicB
2018/03/21 15:53:49 Topic topicC, Key: artist, Value: song, Error: failed to find any partitions for topic topicC
2018/03/21 15:53:54 Topic topicC, Key: cat, Value: rule the world, Error: failed to find any partitions for topic topicC
2018/03/21 15:53:59 Topic topicC, Key: dogs, Value: serve and protect, Error: failed to find any partitions for topic topicC
2018/03/21 15:54:05 Topic topicD, Key: foo, Value: bar, Error: failed to find any partitions for topic topicD
2018/03/21 15:54:10 Topic topicD, Key: artist, Value: song, Error: failed to find any partitions for topic topicD
2018/03/21 15:54:15 Topic topicD, Key: cat, Value: rule the world, Error: failed to find any partitions for topic topicD
$
```

**Comment by aerostitch** [comment] 2018-03-22 00:49
Ok, the retry mechanism is actually already in place built in the `WriteMessages` function. The issue is fixes based on my tests with #85 .
@hryamzik can you confirm that this is what you want? You just have to setup the `MaxAttempts` in your `NewWriter` a little higher than the default (which is `10` https://github.com/segmentio/kafka-go/blob/master/writer.go#L186) if you still see the issue after my fix is in. But the method already supports retries https://github.com/segmentio/kafka-go/blob/master/writer.go#L304 that will wait incrementally from 100ms to 1s between each try.

**Closed** 2018-03-23 20:50 UTC

**Comment by kargakis** [comment] 2019-04-03 17:11
We are seeing this issue intermittently in v0.2.2

**Comment by ccamel** [comment] 2019-04-04 12:37
Same behaviour here observed sporadically (v0.2.2)

**Comment by aerostitch** [comment] 2019-05-23 22:42
Hi,
Can you give more details about your configuration please?
Could you paste the code you are using please?
Are you trying to write to new auto-created topics? Or is it happening when writing to existing topics?
Are you seeing those logs in batches of, let's say 1 full `config.RebalanceInterval` of time?
Thanks,
Joseph
